version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - deps:/app/deps
      - node_modules:/app/node_modules
      - postgres-data:/var/lib/postgresql/data

  client:
    build: ./Dockerfiles/node
    volumes:
      - ./projects/${CLIENT}:/app
    volumes_from:
      - datastore
    ports:
      - 8080:8080
    depends_on:
      - web
    command: "npm run start"

  web:
    build: ./Dockerfiles/phoenix
    volumes:
      - ./projects/${WEB}:/app
    volumes_from:
      - datastore
    ports:
      - 4000:4000
    depends_on:
      - postgres
    command: "mix phoenix.server"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes_from:
      - datastore

volumes:
  deps:
    driver: local
  node_modules:
    driver: local
  postgres-data:
    driver: local
